1. Write a Python Program to Add Two Matrices?
2. Write a Python Program to Multiply Two Matrices?
3. Write a Python Program to Transpose a Matrix?
4. Write a Python Program to Sort Words in Alphabetic Order?
5. Write a Python Program to Remove Punctuation From a String?

In [1]:
import numpy as np

mat1 = np.array([[11,9,4],
        [5,6,8],
        [2,7,7]])
mat2 = np.array([[2,3,4],
        [5,2,1],
        [6,7,7]])

Matsum = np.add(mat1,mat2)
print("The Sum of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,Matsum))

The Sum of two matrix 

[[11  9  4]
 [ 5  6  8]
 [ 2  7  7]]  and 

[[2 3 4]
 [5 2 1]
 [6 7 7]]  is 

[[13 12  8]
 [10  8  9]
 [ 8 14 14]] 


In [2]:
import numpy as np

mat1 = np.array([[13,42,64],
        [3,7,4],
        [9,1,2]])
mat2 = np.array([[2,4,7],
        [55,67,8],
        [8,9,1]])

mulMat = np.dot(mat1,mat2)
print("The product of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,mulMat))

The product of two matrix 

[[13 42 64]
 [ 3  7  4]
 [ 9  1  2]]  and 

[[ 2  4  7]
 [55 67  8]
 [ 8  9  1]]  is 

[[2848 3442  491]
 [ 423  517   81]
 [  89  121   73]] 


In [4]:
def Matrix(n,v=0):
    M=[]             
    for i in range(n):
        
        row =[]
        for j in range(n):
            row.append(v)
        M.append(row)
    return(M)

def crMatrix(n):
    
    M=[]             
    print("Enter the element :")
    for i in range(n):
        row =[]
        for j in range(n):
            row.append(int(input()))
        M.append(row)
    return(M)

def prMatrix(M,n):
    for i in range(n):
        for j in range(n):
            print(M[i][j], end=" ")
        print() 

def tpMatrix(M,n,result):
    for i in range(n):
        for j in range(n):
            result[i][j]= M[j][i]
    return result

n=int(input("Enter N for N x N matrix: "))       
M1 = crMatrix(n)

print("Display Array M1 In Matrix Form")
prMatrix(M1,n)

result = Matrix(n)
result = tpMatrix(M1,n,result)
print("Transposed Matrix")
for r in result:
    print(r)

Enter N for N x N matrix: 4
Enter the element :
1
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
Display Array M1 In Matrix Form
1 1 2 3 
4 5 6 7 
8 9 10 11 
12 13 14 15 
Transposed Matrix
[1, 4, 8, 12]
[1, 5, 9, 13]
[2, 6, 10, 14]
[3, 7, 11, 15]


In [5]:
Arr = input("Enter string")

words = Arr.split()
words.sort()
for word in words:
    print(word)

Enter stringHe is Good
Good
He
is


In [8]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

Arr = input("Enter a string with punctuations")


rem_punc = ""
for i in Arr:
    if i not in punctuations:
        rem_punc = rem_punc + i

# display 
print(rem_punc)

Enter a string with punctuationsHe is good !@#$$%^^&**())}{}{}][":;'<>,../\
He is good 
